image: ubuntu:disco

before_script:
  - apt-get update && apt-get install build-essential cmake qt5-default g++

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - mkdir -v cmake-build-ci && cd cmake-build-ci
    - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
    - make -j
  artifacts:
    paths:
      - cmake-build-ci/
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - cd cmake-build-ci
    - ctest --verbose-about-failures
