version: ci{build}

image:
- Visual Studio 2019

clone_depth: 5

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - mkdir cmake-build-av
  - cd cmake-build-av

build_script:
  - cmd: cmake -DCMAKE_PREFIX_PATH=C:/Qt/6.0/msvc2019_64 -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSSV_BUILD_VERSION="%APPVEYOR_BUILD_VERSION%" ..
  - cmd: ninja

before_test:
  - cmd: copy C:\Qt\6.0\msvc2019_64\bin\Qt6Core.dll .
  - cmd: copy C:\Qt\6.0\msvc2019_64\bin\Qt6Test.dll .

test_script:
  - cmd: test_parser.exe

after_test:
  - mkdir artifact
  - cmd: C:\Qt\6.0\msvc2019_64\bin\windeployqt.exe --dir artifact --release --no-quick-import --no-system-d3d-compiler --compiler-runtime --no-webkit2 --no-opengl-sw stellaris_stat_viewer.exe
  - cmd: copy stellaris_stat_viewer.exe artifact
  
artifacts:
  - path: cmake-build-av\artifact
