version: ci{build}

image:
- Visual Studio 2017
- Ubuntu1804

clone_depth: 5

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install qt5-default
  - mkdir cmake-build-av
  - cd cmake-build-av

build_script:
  - cmd: cmake -DCMAKE_PREFIX_PATH=C:/Qt/5.12/msvc2017_64 -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSSV_BUILD_VERSION="%APPVEYOR_BUILD_VERSION%" ..
  - cmd: nmake
  - sh: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSSV_BUILD_VERSION="$APPVEYOR_BUILD_VERSION" ..
  - sh: make

before_test:
  - cmd: copy C:\Qt\5.12\msvc2017_64\bin\Qt5Core.dll .
  - cmd: copy C:\Qt\5.12\msvc2017_64\bin\Qt5Test.dll .

test_script:
  - cmd: test_parser.exe -o test_result_parser.xml -xunitxml
  - sh: ./test_parser -o test_result_parser.xml -xunitxml

after_test:
  - mkdir artifact
  - cmd: C:\Qt\5.12\msvc2017_64\bin\windeployqt.exe --dir artifact --release --no-quick-import --no-system-d3d-compiler --compiler-runtime --no-webkit2 --no-opengl-sw stellaris_stat_viewer.exe
  - cmd: copy stellaris_stat_viewer.exe artifact
  - sh: cp stellaris_stat_viewer artifact

artifacts:
  - path: cmake-build-av\artifact
