version: 0.0.1-ci{build}

image:
- Visual Studio 2017
- Ubuntu1804

clone_depth: 5

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - sh: sudo apt install qt5-default
  - mkdir cmake-build-av
  - cd cmake-build-av

build_script:
  - cmd: cmake -DCMAKE_PREFIX_PATH=C:/Qt/5.12/msvc2017_64 -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - cmd: nmake
  - sh: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - sh: make

before_test:
  - cmd: copy C:\Qt\5.12\msvc2017_64\bin\Qt5Core.dll .
  - cmd: copy C:\Qt\5.12\msvc2017_64\bin\Qt5Test.dll .

test_script:
#  - ps: >-
#    if ($isWindows) {
#        cp C:\Qt\5.12.1\msvc2017_64\bin\Qt5Test.dll
#        cp C:\Qt\5.12.1\msvc2017_64\bin\Qt5Core.dll
#        .\test_parser.exe -o .\test_result_parser.xml -xunitxml
#    }
  - cmd: test_parser.exe -o test_result_parser.xml -xunitxml
  - sh: ./test_parser -o test_result_parser.xml -xunitxml
#after_test:
#  - ps: >-
#    if ($isWindows) {
#        $wc = New-Object 'System.Net.WebClient'
#        $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_result_parser.xml))
#    }
#  - sh: curl -F "file=" "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
